-- 아래와 같은 TABLE 생성한다.
CREATE TABLE TB_CUST
(
	CUST_ID SERIAL PRIMARY KEY,
	CUST_NAME VARCHAR(50) NOT NULL
)
;

-- 폰 번호를 저장할 컬럼을 추가한다.
ALTER TABLE TB_CUST
ADD COLUMN PHONE_NUMBER VARCHAR(13);

-- 팩스번호 및 이메일 주소를 저장할 커럶을 추가한다. (한번에 2개 추가) 
ALTER TABLE TB_CUST
ADD COLUMN FAX_NUMBER VARCHAR(13),
ADD COLUMN EMAIL_ADDR VARCHAR(50);

--
INSERT INTO TB_CUST
VALUES
	(1, 'KSH', '010-1234-5678', '02-123-1234', 'dbmsexpert@naver.com')
;

COMMIT;

-- 데이터를 입력 후 아래와 같이 NOT NULL을 추가하면 기존에 레코드가 있기 떄문에 에러가 발생한다.
ALTER TABLE TB_CUST
ADD COLUMN CONTACT_NM VARCHAR NOT NULL
;

-- 이런 경우, 해결책은 우선 NULL 조건으로 컬럼을 추가한다.
ALTER TABLE TB_CUST
ADD COLUMN CONTACT_NM VARCHAR NULL
;

-- CONTACT_NM 컬럼을 UPDATE한다.
UPDATE TB_CUST
SET CONTACT_NM = '홍길동'
WHERE CUST_ID = 1
;

COMMIT;

-- ALTER COLUMN으로 NOT NULL로 제약 조건을 준다.
ALTER TABLE TB_CUST
ALTER COLUMN CONTACT_NM SET NOT NULL
;
