-- 실습준비
DROP TABLE CUSTOMER_GROUPS;
DROP TABLE CUSTOMERS;
DROP VIEW CUSTOMER_DATA;

CREATE TABLE CUSTOMER_GROUPS
(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	PHONE VARCHAR NOT NULL,
	EMAIL VARCHAR,
	GROUP_ID INT,
	FOREIGN KEY (GROUP_ID)
	REFERENCES CUSTOMER_GROUPS (ID)
)
;

CREATE TABLE CUSTOMERS
(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	PHONE VARCHAR NOT NULL,
	EMAIL VARCHAR,
	GROUP_ID INT,
	FOREIGN KEY (GROUP_ID)
	REFERENCES CUSTOMER_GROUPS (ID)
)
;

CREATE VIEW CUSTOMER_DATA
AS
SELECT
	C.ID,
	C.NAME,
	G.NAME CUSTOMER_GROUP
FROM
	CUSTOMERS C,
	CUSTOMER_GROUPS G
WHERE
	C.ID = G.GROUP_ID
;

-- EMAIL 컬럼의 이름을 CONTACT_EMAIL로 변경
ALTER TABLE CUSTOMERS
RENAME COLUMN EMAIL TO CONTACT_EMAIL;

-- NAME 컬럼의 이름을 GROUP_NAME으로 변경
-- 해당 컬럼은 기존에 CUSTOMER_DATA 뷰에서 참조하고 있는 컬럼이다.
ALTER TABLE CUSTOMER_GROUPS
RENAME COLUMN NAME TO GROUP_NAME;

-- 컬럼명이 바뀐 것이 뷰에 자동으로 적용된 것을 확인할 수 있다.
CREATE OR REPLACE VIEW public.customer_data
AS
	SELECT
		c.id,
		c.name,
		g.group_name AS customer_group
	FROM
		customers c,
		customer_groups g
	WHERE g.id = c.group_id
;