--
CREATE TABLE LINKS(
	LINK_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(512) NOT NULL,
	URL VARCHAR(1024) NOT NULL UNIQUE
)
;

ALTER TABLE LINKS 
ADD COLUMN ACTIVE BOOLEAN;

--
ALTER TABLE LINKS
DROP COLUMN ACTIVE;

--
ALTER TABLE LINKS
RENAME COLUMN TITLE TO LINK_TILE;


--
ALTER TABLE LINKS
ADD COLUMN TARGET VARCHAR(10);

--
ALTER TABLE LINKS
ALTER COLUMN TARGET
SET DEFAULT '_BLANK';

--
INSERT INTO LINKS
	(LINK_TITLE, URL)
VALUES
	('PostgreSQL', 'http://www.postgresqltutorial.com/')
;

COMMIT;

SELECT * FROM links;

--
ALTER TABLE LINKS
ADD CHECK(TARGET IN('_SELF', '_BLANK', '_PARENT', '_TOP'));

INSERT INTO LINKS
	(LINK_TITLE, URL, TARGET)
VALUES
	('PostgreSQL', 'http://postgresql.org/', 'whatever');