-- 실습 준비
CREATE TABLE ASSETS
(
	ID SERIAL PRIMARY KEY,
	NAME TEXT NOT NULL,
	ASSET_NO VARCHAR(10) NOT NULL,
	DESCRIPTION TEXT,
	LOCATION TEXT,
	ACQUIRED_DATE DATE NOT NULL
)
;

INSERT INTO ASSETS
(
	NAME,
	ASSET_NO,
	LOCATION,
	ACQUIRED_DATE
)
VALUES
	('Server', '10001', 'Server room', '2017-01-01'),
	('UPS', '10002', 'Server room', '2017-01-02')
;

COMMIT;

-- 실습
-- NAME 컬럼의 데이터 타입을 변경
ALTER TABLE ASSETS
ALTER COLUMN NAME TYPE VARCHAR(50)
;

-- 한 번에 N개 컬럼의 데이터 타입을 변경
ALTER TABLE ASSETS
ALTER COLUMN LOCATION TYPE VARCHAR(100),
ALTER COLUMN DESCRIPTION TYPE VARCHAR(500)
;

-- INT형으로 변경하려 했으나 실패
ALTER TABLE ASSETS
ALTER COLUMN ASSET_NO TYPE INT;

-- INT형으로 데이터 타입 변경 성공
ALTER TABLE ASSETS
ALTER COLUMN ASSET_NO TYPE INT USING ASSET_NO::INTEGER
;