--
CREATE TEMP TABLE TB_CUST_TEMP_TEST(CUST_ID INT);

SELECT * FROM TB_CUST_TEMP_TEST;

--
DROP TABLE TB_CUST_TEMP_TEST; 	-- 우선 TABLE 제거
CREATE TABLE TB_CUST_TEMP_TEST	-- 일반 TABLE 생성
(
	CUST_ID SERIAL PRIMARY KEY,
	CUST_NM VARCHAR NOT NULL
)
;

CREATE TEMP TABLE tb_cust_temp_test(cust_id int);	-- 기존에 존재하는 테이블과 이름이 같은 임시 TABLE 생성

SELECT * FROM TB_CUST_TEMP_TEST; 	-- TABLE 조회

DROP TABLE TB_CUST_TEMP_TEST;		-- TABLE 제거

SELECT * FROM TB_CUST_TEMP_TEST;	-- TABLE 조회

