-- TABLE 이름 변경 실습
-- VENDORS TABLE 생성
CREATE TABLE VENDORS
(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
)
;

-- VENDORS TABLE을 SUPPLIERS TABLE로 변경
ALTER TABLE 
	VENDORS
RENAME TO 
	SUPPLIERS;

-- SUPPLIER_GROUPS TABLE 생성
CREATE TABLE SUPPLIER_GROUPS
(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
)
;

-- SUPPLIERS TABLE에 컬럼 추가 후 FK 생성
ALTER TABLE 
	SUPPLIERS 
ADD COLUMN 
	GROUP_ID INT NOT NULL
;

ALTER TABLE
	SUPPLIERS
ADD FOREIGN KEY (GROUP_ID)
REFERENCES SUPPLIERS(ID)
;

-- 아래와 같은 뷰 생성(뷰는 실제하는 데이터가 아닌 보기용)
CREATE VIEW SUPPLIER_DATA AS
SELECT
	S.ID,
	S.NAME,
	G.NAME "GROUP"
FROM
	SUPPLIERS S,
	SUPPLIER_GROUPS G
WHERE G.ID = S.GROUP_ID
;


DROP TABLE SUPPLIERS CASCADE;

--
CREATE TABLE PUBLIC.SUPPLIERS
(
	ID SERIAL NOT NULL,
	"NAME" VARCHAR NOT NULL,
	GROUP_ID INT4 NOT NULL,
	CONSTRAINT VENDORS_PKEY PRIMARY KEY (ID),
	CONSTRAINT SUPPLIERS_GROUP_ID_FKEY FOREIGN KEY (GROUP_ID)
	REFERENCES SUPPLIER_GROUPS(ID)
)
;

ALTER TABLE SUPPLIER_GROUPS RENAME TO GROUPS;

CREATE OR REPLACE VIEW PUBLIC.SUPPLIER_DATA
AS
SELECT
	S.ID,
	S.NAME,
	G.NAME AS "GROUP"
FROM
	SUPPLIERS S,
	GROUPS G
WHERE G.ID = S.ID;