--기본키 실습 - 기본키 생성
CREATE TABLE TB_PRODUCT_PK_TEST
(
	PRODUCT_NO INTEGER,
	DESCRIPTION TEXT,
	PRODUCT_COST NUMERIC
)
;

ALTER TABLE TB_PRODUCT_PK_TEST
ADD PRIMARY KEY (PRODUCT_NO);

-- AUTO INCREMENT
CREATE TABLE TB_PRODUCT_PK_TEST_2
(
	NAME VARCHAR(255)
)
;

INSERT INTO TB_PRODUCT_PK_TEST_2 (NAME)
VALUES
	('MICROSOFT'),
	('IBM'),
	('APPLE'),
	('SAMSUNG')
;

COMMIT;

SELECT * FROM TB_PRODUCT_PK_TEST_2;

ALTER TABLE TB_PRODUCT_PK_TEST_2
ADD COLUMN ID SERIAL PRIMARY KEY;

SELECT * FROM TB_PRODUCT_PK_TEST_2;

-- 기본키 제거
ALTER TABLE TB_PRODUCT_PK_TEST
DROP CONSTRAINT TB_PRODUCT_PK_TEST_PKEY;

ALTER TABLE TB_PRODUCT_PK_TEST_2
DROP CONSTRAINT TB_PRODUCT_PK_TEST_2_PKEY;