--
SELECT NOW()::DATE;
SELECT CURRENT_DATE;
SELECT TO_CHAR(NOW()::DATE, 'DD/MM/YYYY');
SELECT TO_CHAR(NOW()::DATE, 'MON DD, YYYY');

-- 다양한 일자 계산
SELECT
	FIRST_NAME,
	LAST_NAME,
	NOW() - CREATE_DATE AS DIFF
FROM
	CUSTOMER
;

SELECT
	FIRST_NAME,
	LAST_NAME,
	AGE(CREATE_DATE) AS DIFF
FROM
	CUSTOMER
;

--
SELECT
	FIRST_NAME,
	LAST_NAME,
	EXTRACT (YEAR FROM CREATE_DATE) AS YEAR,
	EXTRACT (MONTH FROM CREATE_DATE) AS MONTH,
	EXTRACT (DAY FROM CREATE_DATE) AS DAY
FROM
	CUSTOMER
;

-- 다양한 시간 추출
SELECT
	LOCALTIME,
	EXTRACT(HOUR FROM LOCALTIME) AS HOUR,
	EXTRACT(MINUTE FROM LOCALTIME) AS MINUTE,
	EXTRACT(SECOND FROM LOCALTIME) AS SECOND
;

-- 시간 계산
SELECT
	TIME '10:00' - TIME '02:00' AS DIFF
;

SELECT 
	TIME '10:59' - TIME '02:01' AS DIFF
;

SELECT
	TIME '10:59:59' - TIME '02:01:01' AS DIFF
;

SELECT
	LOCALTIME,
	LOCALTIME + INTERVAL '2 HOURS' AS PLUS_2HOURS,
	LOCALTIME - INTERVAL '2 HOURS' AS MINUS_2HOURS
;

-- TIMESTAMP
SELECT NOW();
SELECT CURRENT_TIMESTAMP;
SELECT TIMEOFDAY();

SELECT
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.MS'),
	TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.US')
;