--
CREATE TABLE SO_HEADERS 
(
	ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INTEGER,
	SHIP_TO VARCHAR (255)
)
;

CREATE TABLE SO_ITEMS
(
	ITEM_ID INTEGER NOT NULL,
	SO_ID INTEGER,
	PRODUCT_ID INTEGER,
	QTY INTEGER,
	NET_PRICE INTEGER,
	PRIMARY KEY(ITEM_ID, SO_ID)
)
;

ALTER TABLE SO_ITEMS
ADD CONSTRAINT FK_SO_HEADERS_ITEMS_ID
FOREIGN KEY (SO_ID) REFERENCES SO_HEADERS(ID)
;

INSERT INTO SO_HEADERS
	(CUSTOMER_ID, SHIP_ID)
VALUES
	(10, '4000 North First Street, CA 95134, USA'),
	(20, '1900 North First Street, CA 95134, USA'),
	(10, '4000 North First Street, CA 95134, USA')
;

COMMIT;

INSERT INTO SO_ITEMS
	(ITEM_ID, SO_ID, PRODUCT_ID, QTY, NET_PRICE)
VALUES
	(1, 1, 1001, 2, 1000),
	(2, 1, 1000, 3, 1500),
	(3, 2, 1000, 4, 1500),
	(1, 2, 1001, 5, 1000),
	(2, 3, 1002, 2, 1700),
	(3, 3, 1003, 1, 2000)
;

COMMIT;

INSERT INTO SO_ITEMS(ITEM_ID, SO_ID, PRODUCT_ID, QTY, NET_PRICE)
VALUES
	(1, 4, 1001, 2, 1000)
;

ALTER TABLE SO_ITEMS
DROP CONSTRAINT FK_SO_HEADERS_ID;

CREATE TABLE SO_ITEMS
(
	ITEM_ID INTEGER NOT NULL,
	SO_ID INTEGER REFERENCES
	SO_HEADERS(ID),
	PRODUCT_ID INTEGER,
	QTY INTEGER,
	NET_PRICE NUMERIC,
	PRIMARY KEY (ITEM_ID, SO_ID)
)
;

--
CREATE TABLE CHILD_TABLE
(
	C1 INTEGER PRIMARY KEY,
	C2 INTEGER,
	C3 INTEGER,
	FOREIGN KEY (C2, C3)
	REFERENCES PARENT_TABLE (P1, P2)
)
;
-- C2 + C3가 P1 + P2에 존재해야 한다.