--
CREATE TABLE INVOICE
(
	ID SERIAL PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
	QTY NUMERIC NOT NULL CHECK(QTY > 0),
	NET_PRICE NUMERIC CHECK(NET_PRICE > 0)
)
;

ALTER TABLE INVOICE
RENAME COLUMN PRODUC_ID TO PRODUCT_ID
;

INSERT INTO INVOICE 
	(PRODUCT_ID, QTY, NET_PRICE)
VALUES
	(NULL, 1, 1)
;

--
CREATE TABLE INVOICE_UPDATE_TEST
(
	ID SERIAL PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
	QTY NUMERIC NOT NULL CHECK(QTY > 0),
	NET_PRICE NUMERIC CHECK (NET_PRICE > 0)
)
;

INSERT INTO INVOICE_UPDATE_TEST
	(PRODUCT_ID, QTY, NET_PRICE)
VALUES
	(1, 1, 1)
;

COMMIT;

UPDATE
	INVOICE_UPDATE_TEST
SET
	PRODUCT_ID = NULL
WHERE
	PRODUCT_ID = 1
;