-- 체크 제약 조건 실습
CREATE TABLE TB_EMP_CHECK_TEST
(
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	BIRTH_DATE DATE CHECK (BIRTH_DATE > '1900-01-01'),
	JOINED_DATE DATE CHECK (JOINED_DATE > BIRTH_DATE),
	SALARY NUMERIC CHECK(SALARY > 0)
)
;

-- 생일은 반드시 1900년 1월 1일 이후여야 한다.
-- 입사일자는 생일보다 반드시 커야한다.
-- 연봉은 0보다 반드시 커야 한다.

INSERT INTO TB_EMP_CHECK_TEST
(
	FIRST_NAME,
	LAST_NAME,
	BIRTH_DATE,
	JOINED_DATE,
	SALARY
)
	VALUES
(
	'JOIN',
	'DOE',
	'1972-01-01',
	'2015-07-01',
	-100000
);

CREATE TABLE TB_EMP_CHECK 
(
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	BIRTH_DATE DATE CHECK (BIRTH_DATE > '1900-01-01'),
	JOINED_DATE DATE CHECK (JOINED_DATE > BIRTH_DATE),
	SALARY NUMERIC CHECK (SALARY > 0)
)
;

ALTER TABLE TB_EMP_CHECK_TEST
ADD CONSTRAINT SALARY_RANGE_CHECK
CHECK (SALARY > 0 AND SALARY <= 10000000000)
;
-- 연봉은 0보다 커야 하고, 100억 이하여야 한다.

ALTER TABLE TB_EMP_CHECK_TEST
ADD CONSTRAINT NAME_CHECK
CHECK (LENGTH(FIRST_NAME) > 0 AND LENGTH(LAST_NAME) > 0)
;
-- 이름은 반드시 존재해야 한다.