-- 고객 (TB_MOIVE_CUST) TABLE을 생성
CREATE TABLE TB_MOVIE_CUST
(
	CUST_ID CHAR(10) PRIMARY Key,
	CUST_NM VARCHAR(50) NOT NULL,
	SEX CHAR(6) CHECK (SEX IN('MAN', 'WOMAN')),
	BIRTH_DATE DATE NOT NULL,
	ADDRESS VARCHAR(200),
	PHONE_NUMBER VARCHAR(13),
	CUST_GRADE CHAR(1) NOT NULL CHECK(CUST_GRADE IN ('S', 'A', 'B', 'C', 'D')),
	JOIN_DT DATE NOT NULL CHECK (JOIN_DT <= EXPIRE_DT),
	EXPIRE_DT DATE NOT NULL DEFAULT TO_DATE('9999-12-31', 'YYYY-MM-DD')
)
;

CREATE TABLE TB_MOVIE_RESV
(
	RESV_NO CHAR(10) PRIMARY KEY,
	MOVIE_ID CHAR(6) NOT NULL,
	MOVIE_THEATER_ID CHAR(6) NOT NULL,
	CUST_ID CHAR(10) REFERENCES TB_MOVIE_CUST(CUST_ID) NOT NULL,
	MOVIE_START_TIME TIMESTAMP NOT NULL CHECK (MOVIE_START_TIME < MOVIE_END_TIME),
	MOVIE_END_TIME TIMESTAMP NOT NULL,
	SEAT_NO CHAR(4) NOT NULL
)
;