-- 실습 준비
CREATE TABLE TB_MEMBER_NULLIF_TEST (
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	GENDER SMALLINT NOT NULL -- 1: MALE, 2: FEMALE
);

INSERT INTO TB_MEMBER_NULLIF_TEST (
	FIRST_NAME,
	LAST_NAME,
	GENDER
)
	VALUES
	('JOHN', 'DOE', 1),
	('DAVID', 'DAVE', 1),
	('BUSH', 'LILY', 2)
;

COMMIT;

-- 여자 대비 남자의 비율 구하기
SELECT 
	(SUM(CASE WHEN GENDER = 1 THEN 1 ELSE 0 END)) / (SUM(CASE WHEN GENDER = 2 THEN 1 ELSE 0 END)) * 100 AS "MALE/FEMALE RATIO"
FROM
	TB_MEMBER_NULLIF_TEST
;

UPDATE TB_MEMBER_NULLIF_TEST
SET GENDER = 1
WHERE GENDER = 2
;

COMMIT;

SELECT 
	(SUM(CASE WHEN GENDER = 1 THEN 1 ELSE 0 END)) / (SUM(CASE WHEN GENDER = 2 THEN 1 ELSE 0 END)) * 100 AS "MALE/FEMALE RATIO"
FROM
	TB_MEMBER_NULLIF_TEST
;

-- NULLIF 사용
SELECT
	(SUM(CASE WHEN GENDER = 1 THEN 1 ELSE 0 END)) / NULLIF(SUM(CASE WHEN GENDER = 2 THEN 1 ELSE 0 END), 0) * 100 AS "MALE/FEMALE RATIO"
FROM
	TB_MEMBER_NULLIF_TEST
;