--아래 BASKET TABLE에서 FRUIT 컬럼이 중복된 행을 삭제하는 DELETE문을 작성하시오. 단, ROW_NUMBER() 함수를 사용하시오.
CREATE TABLE BASKET(
	ID SERIAL PRIMARY KEY,
	FRUIT VARCHAR(50) NOT NULL
)
;

INSERT INTO BASKET(FRUIT)
VALUES
	('APPLE'),
	('APPLE'),
	('ORANGE'),
	('ORANGE'),
	('ORANGE'),
	('BANANA')
;

COMMIT;