--
SELECT
	FILM_ID,
	TITLE,
	(
	CASE
	WHEN LENGTH < 30 THEN 'SHORT'
	WHEN LENGTH >= 30 AND LENGTH < 90 THEN 'MEDIUM'
	WHEN LENGTH > 90 THEN 'LONG'
	END	) LENGTH
FROM
	FILM
;

WITH TMP1 AS (
	SELECT
		FILM_ID,
		TITLE,
		(
		CASE
		WHEN LENGTH < 30 THEN 'SHORT'
		WHEN LENGTH >= 30 AND LENGTH < 90 THEN 'MEDIUM'
		WHEN LENGTH > 90 THEN 'LONG'
		END	) LENGTH
	FROM
		FILM
)
SELECT * FROM TMP1;

WITH TMP1 AS (
	SELECT
		FILM_ID,
		TITLE,
		(
		CASE
		WHEN LENGTH < 30 THEN 'SHORT'
		WHEN LENGTH >= 30 AND LENGTH < 90 THEN 'MEDIUM'
		WHEN LENGTH > 90 THEN 'LONG'
		END	) LENGTH
	FROM
		FILM
)
SELECT * FROM TMP1 WHERE LENGTH = 'LONG';