-- FIRST_VALUE 실습
SELECT
	A.PRODUCT_NAME,
	B.GROUP_NAME,
	A.PRICE,
	FIRST_VALUE (A.PRICE) OVER
	(PARTITION BY B.GROUP_NAME ORDER BY PRICE) AS LOWEST_PRICE_PER_GROUP
FROM
	PRODUCT A
INNER JOIN PRODUCT_GROUP B
ON (A.GROUP_ID = B.GROUP_ID)
;

-- LAST_VALUE 실습
SELECT
	A.PRODUCT_NAME,
	B.GROUP_NAME,
	A.PRICE,
	LAST_VALUE (A.PRICE) OVER
	(PARTITION BY B.GROUP_NAME ORDER BY A.PRICE
	RANGE BETWEEN UNBOUNDED PRECEDING
	AND UNBOUNDED FOLLOWING)
FROM 
	PRODUCT A
INNER JOIN PRODUCT_GROUP B
ON (A.GROUP_ID = B.GROUP_ID)
;