-- ROW_NUMBER 함수 실습 - 무조건 1,2,3,4,···
SELECT
	A.PRODUCT_NAME,
	B.GROUP_NAME,
	A.PRICE,
	ROW_NUMBER() OVER
	(PARTITION BY B.GROUP_NAME ORDER BY A.PRICE)
FROM
	PRODUCT A
INNER JOIN PRODUCT_GROUP B
ON (A.GROUP_ID = B.GROUP_ID)
;
-- 해당 집합 내에서 순위를 구함
-- 순위를 구할 때 GROUP_NAME 컬럼 기준으로 구함
-- GROUP_NAME 기준의 각 순위는 PRICE 컬럼 기준으로 정렬

--RANK 함수
SELECT
	A.PRODUCT_NAME,
	B.GROUP_NAME,
	A.PRICE,
	RANK() OVER
	(PARTITION BY B.GROUP_NAME ORDER BY PRICE)
FROM
	PRODUCT A
INNER JOIN PRODUCT_GROUP B 
ON (A.GROUP_ID = B.GROUP_ID)
;

--DENSE RANK 함수
SELECT
	A.PRODUCT_NAME,
	B.GROUP_NAME,
	A.PRICE,
	DENSE_RANK() OVER
	(PARTITION BY B.GROUP_NAME ORDER BY A.PRICE)
FROM
	PRODUCT A
INNER JOIN PRODUCT_GROUP B
ON (A.GROUP_ID = B.GROUP_ID)
;