-- 실습 준비
CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	MANAGER_ID INT,
	FOREIGN KEY (MANAGER_ID)
	REFERENCES EMPLOYEE (EMPLOYEE_ID)
	ON DELETE CASCADE
)
;

INSERT INTO EMPLOYEE
(
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	MANAGER_ID
)
VALUES
(1, 'WINDY', 'HAYS', NULL),
(2, 'AVA', 'CHRISTENSEN', 1),
(3, 'HASSAN', 'CONNER', 1),
(4, 'ANNA', 'REEVES', 2),
(5, 'SAU', 'NORMAN', 2),
(6, 'KELSIE', 'HAYS', 3),
(7, 'TORY', 'GOFF', 3),
(8, 'SALLEY', 'LESTER', 3)
;

SELECT * FROM employee;

--
SELECT
	E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE,
	M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER
FROM
	EMPLOYEE E
INNER JOIN EMPLOYEE M
ON M.EMPLOYEE_ID = E.MANAGER_ID
ORDER BY
	MANAGER
;

--
SELECT
	E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE,
	M.FIRST_NAME || ' ' || E.LAST_NAME MANAGER
FROM
	EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON M.EMPLOYEE_ID = E.MANAGER_ID
ORDER BY 
	MANAGER
;

--
SELECT
	F1.TITLE,
	F2.TITLE,
	F1.LENGTH
FROM
	FILM F1
INNER JOIN FILM F2
ON F1.TITLE <> F2.TITLE
AND F1.LENGTH = F2.LENGTH
;